[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    refreshPeriod = "168h"
[".asdf".pull]
    args = ["--ff-only"]
[".asdf".clone]
    args = ["-b", "v0.14.1"]

[".zinit"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "168h"
[".zinit".pull]
    args = ["--ff-only"]
