import = [
    "~/.config/alacritty/themes/one_dark.toml"
]

[font]
normal = { family = "Cascadia Code NF", style = "Regular" }
size = 18

[window]
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
decorations = "Transparent"

[keyboard]
bindings = [
  { key = "T", mods = "Command", action = "None" }
]
