theme = "onedark"

[editor]
line-number = "relative"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicataor", "file-modification-indicator"]
